In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv("/content/rainfall.csv")

In [75]:
df.head()

         date  rainfall  temperature  humidity  wind_speed weather_condition
0  2022-01-01      12.5         15.2      78.0         8.5             Rainy
1  2022-01-02       8.2         17.8      65.0         5.2             Rainy
2  2022-01-03       0.0         20.1      52.0         3.1             Sunny
3  2022-01-04       3.7         18.6      71.0         6.7             Rainy
4  2022-01-05      21.1         14.8      82.0         9.3             Rainy

In [76]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     object
 1   rainfall           53 non-null     float64
 2   temperature        53 non-null     float64
 3   humidity           53 non-null     float64
 4   wind_speed         53 non-null     float64
 5   weather_condition  53 non-null     object
dtypes: float64(4), object(2)
memory usage: 2.7+ KB

        rainfall  temperature   humidity  wind_speed
count  53.000000    53.000000  53.000000   53.000000
mean    9.049057    17.950943  69.245283    6.403774
std     6.712521     2.500663  11.969361    2.209069
min     0.000000    13.900000  44.000000    2.100000
25%     3.900000    16.100000  62.000000    4.700000
50%     8.300000    17.800000  72.000000    6.700000
75%    14.800000    19.400000  78.000000    8.300000
max    21.800000    23.400000  89.000000   10.500000

In [77]:
df.tail()

          date  rainfall  temperature  humidity  wind_speed weather_condition
49  2022-02-19      17.3         15.9      83.0         8.6             Rainy
50  2022-02-20       9.6         18.6      71.0         6.7             Rainy
51  2022-02-21       0.0         21.3      55.0         5.1             Sunny
52  2022-02-22       7.4         16.8      77.0         8.9             Rainy
53          Co       NaN          NaN       NaN         NaN               NaN

In [78]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 54
Columns: 6

In [79]:
df.dtypes

date                  object
rainfall             float64
temperature          float64
humidity             float64
wind_speed           float64
weather_condition     object
dtype: object

In [80]:
#Finding Missing Values
df.isnull().sum()

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

In [81]:
#Filling Missing Values
num_cols = ["rainfall","temperature","humidity","wind_speed"]
df[num_cols] = df[num_cols].fillna(df[num_cols].mean()) # for numerical data we are filling with mean

In [82]:
#Filling Missing Categorical Values
df["weather_condition"] = df["weather_condition"].fillna(df["weather_condition"].mode()[0]) #for categorical data we use mode

In [83]:
#Converting Date Column
df["date"] = pd.to_datetime(df["date"], errors="coerce")

In [84]:
#Rename Columns to Lowercase to handle inconsistency
df.columns = df.columns.str.lower()
df["weather_condition"] = df["weather_condition"].str.lower()

In [85]:
#Removing Duplicate Rows
df = df.drop_duplicates()

In [86]:
#Increase Rainfall by 10%
df["rainfall"] = df["rainfall"] * 1.10

In [87]:
df["rain_category"] = df["rainfall"].apply(lambda x: "Heavy Rain" if x > 10 else "Light Rain")#Creates a new feature based on rainfall.
df[df["rainfall"] > 10] #Filtering Dataset , Returns only rows where rainfall is greater than 10 mm.

,date,rainfall,temperature,humidity,wind_speed,weather_condition,rain_category
0,2022-01-01,13.75,15.2,78.0,8.5,rainy,Heavy Rain
4,2022-01-05,23.21,14.8,82.0,9.3,rainy,Heavy Rain
5,2022-01-06,16.83,16.5,75.0,7.8,rainy,Heavy Rain
8,2022-01-09,12.32,17.3,73.0,6.1,rainy,Heavy Rain
9,2022-01-10,20.46,15.8,79.0,8.9,rainy,Heavy Rain
10,2022-01-11,10.45,16.2,72.0,5.7,rainy,Heavy Rain
14,2022-01-15,16.39,15.1,81.0,8.7,rainy,Heavy Rain
15,2022-01-16,21.12,16.8,77.0,7.2,rainy,Heavy Rain
18,2022-01-19,11.88,17.6,75.0,6.7,rainy,Heavy Rain
19,2022-01-20,17.93,14.5,84.0,9.1,rainy,Heavy Rain
23,2022-01-24,13.97,15.7,79.0,8.3,rainy,Heavy Rain
24,2022-01-25,20.24,17.1,76.0,6.8,rainy,Heavy Rain
25,2022-01-26,10.78,19.7,62.0,4.7,rainy,Heavy Rain
28,2022-01-29,17.05,14.2,83.0,9.5,rainy,Heavy Rain
29,2022-01-30,23.98,16.4,78.0,7.6,rainy,Heavy Rain
30,2022-01-31,12.76,19.1,65.0,5.1,rainy,Heavy Rain
33,2022-02-03,10.01,15.4,81.0,8.9,rainy,Heavy Rain
34,2022-02-04,19.69,16.7,77.0,6.2,rainy,Heavy Rain
38,2022-02-08,14.52,14.7,85.0,9.3,rainy,Heavy Rain
39,2022-02-09,21.56,16.2,79.0,7.8,rainy,Heavy Rain
40,2022-02-10,11.44,19.5,66.0,5.5,rainy,Heavy Rain
43,2022-02-13,16.28,13.9,87.0,9.9,rainy,Heavy Rain
44,2022-02-14,22.55,15.6,81.0,8.2,rainy,Heavy Rain
48,2022-02-18,13.09,14.1,89.0,10.5,rainy,Heavy Rain
49,2022-02-19,19.03,15.9,83.0,8.6,rainy,Heavy Rain
50,2022-02-20,10.56,18.6,71.0,6.7,rainy,Heavy Rain

In [88]:
#Droping Unnecessary Column
df = df.drop(columns=["wind_speed"])

In [89]:
#One-Hot Encoding-converting text to numerical
df = pd.get_dummies(df, columns=["weather_condition"])

In [90]:
#Sorting Dataset By date
df.sort_values(by="date")

,date,rainfall,temperature,humidity,rain_category,weather_condition_rainy,weather_condition_sunny
0,2022-01-01,13.750000,15.200000,78.000000,Heavy Rain,True,False
1,2022-01-02,9.020000,17.800000,65.000000,Light Rain,True,False
2,2022-01-03,0.000000,20.100000,52.000000,Light Rain,False,True
3,2022-01-04,4.070000,18.600000,71.000000,Light Rain,True,False
4,2022-01-05,23.210000,14.800000,82.000000,Heavy Rain,True,False
5,2022-01-06,16.830000,16.500000,75.000000,Heavy Rain,True,False
6,2022-01-07,7.480000,19.200000,61.000000,Light Rain,True,False
7,2022-01-08,0.000000,21.700000,48.000000,Light Rain,False,True
8,2022-01-09,12.320000,17.300000,73.000000,Heavy Rain,True,False
9,2022-01-10,20.460000,15.800000,79.000000,Heavy Rain,True,False
10,2022-01-11,10.450000,16.200000,72.000000,Heavy Rain,True,False
11,2022-01-12,2.310000,19.800000,58.000000,Light Rain,True,False
12,2022-01-13,0.000000,22.400000,45.000000,Light Rain,False,True
13,2022-01-14,8.140000,17.900000,69.000000,Light Rain,True,False
14,2022-01-15,16.390000,15.100000,81.000000,Heavy Rain,True,False
15,2022-01-16,21.120000,16.800000,77.000000,Heavy Rain,True,False
16,2022-01-17,6.160000,18.500000,63.000000,Light Rain,True,False
17,2022-01-18,0.000000,21.200000,51.000000,Light Rain,False,True
18,2022-01-19,11.880000,17.600000,75.000000,Heavy Rain,True,False
19,2022-01-20,17.930000,14.500000,84.000000,Heavy Rain,True,False
20,2022-01-21,4.290000,16.100000,71.000000,Light Rain,True,False
21,2022-01-22,0.000000,19.400000,59.000000,Light Rain,False,True
22,2022-01-23,7.810000,18.200000,67.000000,Light Rain,True,False
23,2022-01-24,13.970000,15.700000,79.000000,Heavy Rain,True,False
24,2022-01-25,20.240000,17.100000,76.000000,Heavy Rain,True,False
25,2022-01-26,10.780000,19.700000,62.000000,Heavy Rain,True,False
26,2022-01-27,0.000000,22.900000,47.000000,Light Rain,False,True
27,2022-01-28,6.820000,18.500000,70.000000,Light Rain,True,False
28,2022-01-29,17.050000,14.200000,83.000000,Heavy Rain,True,False
29,2022-01-30,23.980000,16.400000,78.000000,Heavy Rain,True,False
30,2022-01-31,12.760000,19.100000,65.000000,Heavy Rain,True,False
31,2022-02-01,0.000000,21.600000,53.000000,Light Rain,False,True
32,2022-02-02,4.730000,17.200000,73.000000,Light Rain,True,False
33,2022-02-03,10.010000,15.400000,81.000000,Heavy Rain,True,False
34,2022-02-04,19.690000,16.700000,77.000000,Heavy Rain,True,False
35,2022-02-05,8.250000,18.900000,64.000000,Light Rain,True,False
36,2022-02-06,0.000000,22.100000,49.000000,Light Rain,False,True
37,2022-02-07,6.380000,17.800000,72.000000,Light Rain,True,False
38,2022-02-08,14.520000,14.700000,85.000000,Heavy Rain,True,False
39,2022-02-09,21.560000,16.200000,79.000000,Heavy Rain,True,False
40,2022-02-10,11.440000,19.500000,66.000000,Heavy Rain,True,False
41,2022-02-11,0.000000,23.400000,44.000000,Light Rain,False,True
42,2022-02-12,7.370000,18.100000,74.000000,Light Rain,True,False
43,2022-02-13,16.280000,13.900000,87.000000,Heavy Rain,True,False
44,2022-02-14,22.550000,15.600000,81.000000,Heavy Rain,True,False
45,2022-02-15,9.130000,19.200000,68.000000,Light Rain,True,False
46,2022-02-16,0.000000,22.700000,51.000000,Light Rain,False,True
47,2022-02-17,5.610000,17.400000,75.000000,Light Rain,True,False
48,2022-02-18,13.090000,14.100000,89.000000,Heavy Rain,True,False
49,2022-02-19,19.030000,15.900000,83.000000,Heavy Rain,True,False
50,2022-02-20,10.560000,18.600000,71.000000,Heavy Rain,True,False
51,2022-02-21,0.000000,21.300000,55.000000,Light Rain,False,True
52,2022-02-22,8.140000,16.800000,77.000000,Light Rain,True,False
53,NaT,9.953962,17.950943,69.245283,Light Rain,True,False

In [91]:
#Detecing & Handling Outliers
Q1 = df["rainfall"].quantile(0.25)
Q3 = df["rainfall"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df["rainfall"] >= lower) & (df["rainfall"] <= upper)]

In [92]:
df.head() # 1st 5 rows After Dataset cleaning

,date,rainfall,temperature,humidity,rain_category,weather_condition_rainy,weather_condition_sunny
0,2022-01-01,13.75,15.2,78.0,Heavy Rain,True,False
1,2022-01-02,9.02,17.8,65.0,Light Rain,True,False
2,2022-01-03,0.00,20.1,52.0,Light Rain,False,True
3,2022-01-04,4.07,18.6,71.0,Light Rain,True,False
4,2022-01-05,23.21,14.8,82.0,Heavy Rain,True,False

In [93]:
df.tail() ## last 5 rows After Dataset cleaning

,date,rainfall,temperature,humidity,rain_category,weather_condition_rainy,weather_condition_sunny
49,2022-02-19,19.030000,15.900000,83.000000,Heavy Rain,True,False
50,2022-02-20,10.560000,18.600000,71.000000,Heavy Rain,True,False
51,2022-02-21,0.000000,21.300000,55.000000,Light Rain,False,True
52,2022-02-22,8.140000,16.800000,77.000000,Light Rain,True,False
53,NaT,9.953962,17.950943,69.245283,Light Rain,True,False

In [94]:
df.to_csv("cleaned_rainfall.csv", index=False)
from google.colab import files
files.download("cleaned_rainfall.csv")